### ISSUE TITLE
建议加入canvas-nest.js参数的设定

### ISSUE THREAD

**Issue by maboloshi** [theme-next/theme-next-canvas-nest#1]
原项目`canvas-nest.js`有4个参数 进行自定义，希望加入

**Comment by ivan-nginx** [comment]
請用英文寫。

**Comment by sli1989** [comment]
The feature has been add in PR [#441](https://github.com/theme-next/hexo-theme-next/pull/441). ENJOY IT.
Any optimization is welcome.

**Comment by stevenjoezhang** [comment]
安装方式已更新，请查看最新的 README ： https://github.com/theme-next/theme-next-canvas-nest/blob/master/README.md
