### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by JOduMonT** [theme-next/theme-next-canvas-nest#3]
the plugins is not working

with **lighthouse** (_chrome dev plugin_) I have this error in **canvas-nest.min.js:1** 
`Uncaught SyntaxError: Unexpected token <`

I'm using :
```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Linux 4.15.0-39-generic linux x64
http_parser: 2.8.0
node: 8.12.0
v8: 6.2.414.66
uv: 1.19.2
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.32.0
napi: 3
openssl: 1.0.2p
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
```
with `next theme`

Is their a way I could give you more information ?

Regards

Jonathan

**Comment by ivan-nginx** [comment]
Can you explain your installation steps?

**Comment by JOduMonT** [comment]
sorry for my late reply;

_I forgot about this issue when I used the CDN instead_

obviously I was trying to install it in a silly way like
but my goal was to only pulling code and avoid edition or forking
for in short:

`git submodule add https://github.com/theme-next/hexo-theme-next themes/next`

than
`git submodule add https://github.com/theme-next/theme-next-canvas-nest themes/next/source/lib/canvas-nest`

PS: we could leave this issue close as using the CDN is at 90% the solution
