### ISSUE TITLE
SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by guomaoqiu** [theme-next/theme-next-canvas-nest#4]
![image](https://user-images.githubusercontent.com/9714859/49795059-06633a00-fd74-11e8-8fc8-f101a99f2353.png)
![image](https://user-images.githubusercontent.com/9714859/49795081-12e79280-fd74-11e8-87d8-729ab578649e.png)

**Comment by ivan-nginx** [comment]
@guomaoqiu same as #3, step by step please.
