### ISSUE TITLE
My page cannot generate animation

### ISSUE THREAD

**Issue by Cynthia0329** [theme-next/theme-next-canvas-nest#5]
- ![](https://raw.githubusercontent.com/Cynthia0329/images/master/img/20190423145422.png)

- ![](https://raw.githubusercontent.com/Cynthia0329/images/master/img/20190423145900.png)

- [My page has none](https://raw.githubusercontent.com/Cynthia0329/images/master/img/20190423145936.png)

**Comment by stevenjoezhang** [comment]
Any URLs?

**Comment by HACLANG** [comment]
Excuse me, when will this problem be fixed?
Thank

**Comment by stevenjoezhang** [comment]
@HACLANG Please provide your blog's url
